### ISSUE TITLE
(not production ready too much bugs - waste of time)

### ISSUE THREAD

**Issue by kgnfth** [krane/krane#35]

**Comment by jalvarado91** [comment]
Are you intending on running the krane host locally or in a remote machine? Note that step 1 should be done in the host running docker. 

A common error when running the host locally on macOS is that krane will expect your public key to be under ./ssh/authorized_keys whereas usually for macOS it might be under known_hosts

**Comment by kgnfth** [comment]
@jalvarado91 im running it remote and my public key is under ./ssh/authorized_keys and my private under ./ssh
i am using `id_ed25519` and id_ed25519.pub is inside  ./ssh/authorized_keys

**Comment by david-castaneda** [comment]
Hey @kgnfth thanks for trying out Krane just to get some insight what kind of errors or bugs did you encounter? If you had specific bugs you want to report feel free to assign them to me and i'll take a look!
